import { render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { describe, expect, it } from 'vitest'

import type { DocumentItem } from '../../services/documents'
import type { DocumentInsights } from '../../services/insights'
import { errorEnvelope, json, mockFetch } from '../../test/mockFetch'
import { InsightsPanel } from './InsightsPanel'

const DOCUMENT: DocumentItem = {
  id: 'doc-1',
  knowledge_base_id: 'kb-1',
  filename: 'ml.pdf',
  extension: '.pdf',
  content_type: 'application/pdf',
  size_bytes: 1000,
  status: 'completed',
  error_message: null,
  page_count: 42,
  chunk_count: 120,
  created_at: '2026-09-30T10:00:00Z',
  processing_started_at: null,
  processed_at: '2026-09-30T10:01:00Z',
  extracted_metadata: {
    title: 'Machine Learning',
    author: null,
    document_date: null,
    word_count: 4600,
    character_count: 30000,
    section_count: 7,
    table_count: 0,
  },
}

const READY: DocumentInsights = {
  status: 'ready',
  content: {
    language: 'English',
    short_summary: 'An introduction to machine learning.',
    detailed_summary: 'Part one covers CNNs.\n\nPart two covers transformers.',
    technical_summary: 'CNNs use convolution layers; transformers use attention.',
    key_points: ['CNNs learn spatial features', 'Attention relates all tokens'],
    topics: ['Deep learning', 'Classification'],
    keywords: ['CNN', 'transformer'],
    entities: [
      { name: 'Geoffrey Hinton', type: 'person' },
      { name: 'PyTorch', type: 'technology' },
      { name: 'TensorFlow', type: 'technology' },
    ],
    ungrounded_removed: 2,
  },
  model: 'claude-opus-5',
  input_tokens: 12000,
  output_tokens: 900,
  llm_calls: 1,
  coverage: 1,
  error_message: null,
  requested_at: '2026-10-01T10:00:00Z',
  generated_at: new Date().toISOString(),
}

const NONE: DocumentInsights = { ...READY, status: 'none', content: null, model: null, llm_calls: 0, input_tokens: 0, output_tokens: 0, coverage: null, generated_at: null, requested_at: null }

describe('InsightsPanel', () => {
  it('generates insights on request and shows them when ready', async () => {
    let state: DocumentInsights = NONE
    const spy = mockFetch({
      'GET /documents/doc-1/insights': () => {
        const current = state
        if (state.status === 'pending') state = READY // the worker finishes before the next poll
        return json(current)
      },
      'POST /documents/doc-1/insights': () => {
        state = { ...NONE, status: 'pending', requested_at: '2026-10-01T10:00:00Z' }
        return json(state, 202)
      },
    })
    render(<InsightsPanel document={DOCUMENT} />)

    await userEvent.click(await screen.findByRole('button', { name: 'Generate insights' }))

    expect(screen.getByRole('status')).toHaveTextContent('Generating insights…')
    expect(await screen.findByText('An introduction to machine learning.', {}, { timeout: 6000 })).toBeInTheDocument()
    expect(spy.mock.calls.filter(([, init]) => init?.method === 'POST')).toHaveLength(1)
  })

  it('shows every kind of insight', async () => {
    mockFetch({ 'GET /documents/doc-1/insights': () => json(READY) })
    render(<InsightsPanel document={DOCUMENT} />)

    await screen.findByText('An introduction to machine learning.')
    await userEvent.click(screen.getByRole('tab', { name: 'Technical' }))
    expect(screen.getByRole('tabpanel')).toHaveTextContent('CNNs use convolution layers; transformers use attention.')
    await userEvent.click(screen.getByRole('tab', { name: 'Detailed' }))
    expect(within(screen.getByRole('tabpanel')).getAllByText(/Part (one|two)/)).toHaveLength(2) // two paragraphs

    expect(within(screen.getByRole('region', { name: 'Key points' })).getAllByRole('listitem')).toHaveLength(2)
    expect(within(screen.getByRole('region', { name: 'Topics' })).getByText('Deep learning')).toBeInTheDocument()
    expect(within(screen.getByRole('region', { name: 'Keywords' })).getByText('transformer')).toBeInTheDocument()
    const entities = screen.getByRole('region', { name: 'Entities' })
    expect(within(entities).getByText('Technologies:').nextElementSibling).toHaveTextContent('PyTorch, TensorFlow')
    expect(within(entities).getByText('People:').nextElementSibling).toHaveTextContent('Geoffrey Hinton')
    const stats = screen.getByRole('region', { name: 'Document statistics' })
    expect(within(stats).getByText('Reading time').nextElementSibling).toHaveTextContent('20 min')
    expect(screen.getByText(/AI-generated by claude-opus-5 from the whole document/)).toHaveTextContent(
      /English · 1 AI call · 12,000 input \/ 900 output tokens · 2 terms not found in the document removed/,
    )
  })

  it('says when only part of a very long document was read', async () => {
    mockFetch({ 'GET /documents/doc-1/insights': () => json({ ...READY, coverage: 0.4, llm_calls: 7 }) })
    render(<InsightsPanel document={DOCUMENT} />)

    expect(await screen.findByText(/from 40% of the document \(an even sample/)).toBeInTheDocument()
  })

  it('shows a failure and lets the user try again', async () => {
    mockFetch({
      'GET /documents/doc-1/insights': () =>
        json({ ...NONE, status: 'failed', error_message: 'The AI model is busy right now. Please try again shortly.' }),
      'POST /documents/doc-1/insights': () =>
        errorEnvelope(503, 'llm_not_configured', 'The AI model is not configured. Set LLM_API_KEY in .env and restart.'),
    })
    render(<InsightsPanel document={DOCUMENT} />)

    expect(await screen.findByText('The AI model is busy right now. Please try again shortly.')).toBeInTheDocument()
    await userEvent.click(screen.getByRole('button', { name: 'Regenerate' }))
    expect(await screen.findByText(/not configured/)).toBeInTheDocument()
  })
})
