import uuid
from datetime import datetime
from enum import StrEnum
from typing import Any

from sqlalchemy import DateTime, Enum, Float, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base, TimestampMixin


class InsightStatus(StrEnum):
    PENDING = "pending"  # queued or being generated by a worker
    READY = "ready"
    FAILED = "failed"


class DocumentInsight(TimestampMixin, Base):
    """AI-generated summaries, key points, topics, keywords and entities for one document.
    At most one per document; regenerating replaces it."""

    __tablename__ = "document_insights"

    document_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"), primary_key=True
    )
    status: Mapped[InsightStatus] = mapped_column(
        Enum(
            InsightStatus,
            name="insight_status",
            native_enum=False,
            create_constraint=True,
            length=16,
            values_callable=lambda enum: [member.value for member in enum],
        ),
        nullable=False,
    )
    # See schemas.insights.InsightContent.
    content: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    model: Mapped[str | None] = mapped_column(String(100))
    input_tokens: Mapped[int] = mapped_column(Integer, default=0, server_default="0", nullable=False)
    output_tokens: Mapped[int] = mapped_column(Integer, default=0, server_default="0", nullable=False)
    llm_calls: Mapped[int] = mapped_column(Integer, default=0, server_default="0", nullable=False)
    # Share of the document's text the model read (1.0 unless a very long document was sampled).
    coverage: Mapped[float | None] = mapped_column(Float)
    error_message: Mapped[str | None] = mapped_column(Text)
    requested_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    generated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
