"""Document insights: summaries, key points, topics, keywords and entities, generated by the LLM.

    API (request) ──► document_insights row: pending ──► job queue ──► worker (generate) ──► ready / failed

The text comes from the document's indexed passages, in order. A document that fits in one
call is analysed in one call; a longer one is analysed in parts whose analyses are then
merged ("map-reduce"). Past `insights_max_parts` parts, an even sample of the document is
analysed and the share actually read is stored as `coverage` and shown, never hidden.

The model's output is constrained to a JSON schema (structured outputs), then validated and
cleaned. Keywords and entity names are kept only if they occur in the text the model read,
so an invented entity can't appear as if it came from the document.
"""

import json
import logging
import uuid
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from typing import Any

from pydantic import ValidationError
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from app.core.config import get_settings
from app.core.errors import ConflictError
from app.core.providers import llm_configured
from app.db.session import SessionLocal
from app.llm import factory as llm_factory
from app.llm.base import LLMError, LLMNotConfiguredError, LLMProvider, Message
from app.models import Document, DocumentChunk, DocumentInsight, DocumentStatus, InsightStatus
from app.schemas.insights import ENTITY_TYPES, InsightContent, InsightRead
from app.services import document_service

logger = logging.getLogger(__name__)

# A request still pending after this long lost its job (e.g. Redis was flushed): allow a new one.
STALE_PENDING_AFTER = timedelta(minutes=30)
_MAX_OUTPUT_TOKENS = 8000
_GENERIC_FAILURE = "The insights could not be generated because of an internal error. Try again."

_STRING_LIST = {"type": "array", "items": {"type": "string"}}
INSIGHT_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        # First, so the model states the document's language before writing anything in it.
        "language": {"type": "string"},
        "short_summary": {"type": "string"},
        "detailed_summary": {"type": "string"},
        "technical_summary": {"type": "string"},
        "key_points": _STRING_LIST,
        "topics": _STRING_LIST,
        "keywords": _STRING_LIST,
        "entities": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "type": {"type": "string", "enum": list(ENTITY_TYPES)},
                },
                "required": ["name", "type"],
                "additionalProperties": False,
            },
        },
    },
    "required": [
        "language",
        "short_summary",
        "detailed_summary",
        "technical_summary",
        "key_points",
        "topics",
        "keywords",
        "entities",
    ],
    "additionalProperties": False,
}

_FIELDS = """\
- language: the language the document text is written in, named in English (for example "English").
- short_summary: one or two sentences saying what the document is and its main conclusion.
- detailed_summary: two to four paragraphs (separated by a blank line) covering its content in order.
- technical_summary: the concrete specifics: methods, architecture, parameters, figures, rules, \
procedures and requirements. If the document has none, summarise its concrete facts and numbers.
- key_points: five to eight standalone statements a reader must not miss.
- topics: three to six short subject labels (two or three words each).
- keywords: eight to fifteen important terms, written exactly as they appear in the text.
- entities: up to fifteen named people, organizations, locations, products, technologies and \
dates, with the name exactly as written in the text."""

ANALYSIS_SYSTEM_PROMPT = f"""\
You analyse one document for a personal knowledge base. Use only the document text you are \
given: do not add facts, numbers, names or opinions that are not in it. Write every field in \
the language the document is written in, the `language` you report: an English document gets \
an English analysis. Labels like [Page 3] or [Section: ...] mark where the text comes from; \
don't mention them.

Return:
{_FIELDS}"""

MERGE_SYSTEM_PROMPT = f"""\
You are given analyses of consecutive parts of one document, as JSON, in document order. \
Merge them into a single analysis of the whole document: combine and deduplicate, keep what \
matters most, and do not add anything that is not in the part analyses. Write in the \
language the part analyses report.

Return:
{_FIELDS}"""


class InsightGenerationError(Exception):
    """Generation failed; the message is safe to show to the user."""


# --- reading ------------------------------------------------------------------------------------


def _read(document_id: uuid.UUID, insight: DocumentInsight | None) -> InsightRead:
    if insight is None:
        return InsightRead(status="none")
    return InsightRead(
        status=insight.status.value,
        content=InsightContent.model_validate(insight.content) if insight.content else None,
        model=insight.model,
        input_tokens=insight.input_tokens,
        output_tokens=insight.output_tokens,
        llm_calls=insight.llm_calls,
        coverage=insight.coverage,
        error_message=insight.error_message,
        requested_at=insight.requested_at,
        generated_at=insight.generated_at,
    )


async def get(db: AsyncSession, user_id: uuid.UUID, document_id: uuid.UUID) -> InsightRead:
    await document_service.get_owned(db, user_id, document_id)
    return _read(document_id, await db.get(DocumentInsight, document_id))


# --- requesting -----------------------------------------------------------------------------------


async def _mark_pending(db: AsyncSession, document_id: uuid.UUID) -> DocumentInsight:
    """Pending, keeping any previous content visible until the new run replaces it."""
    insight = await db.get(DocumentInsight, document_id)
    now = datetime.now(UTC)
    if insight is None:
        insight = DocumentInsight(document_id=document_id, status=InsightStatus.PENDING, requested_at=now)
        db.add(insight)
    else:
        insight.status = InsightStatus.PENDING
        insight.requested_at = now
        insight.error_message = None
    await db.commit()
    await db.refresh(insight)
    return insight


async def request(db: AsyncSession, queue: Any, user_id: uuid.UUID, document_id: uuid.UUID) -> InsightRead:
    """Queue (re)generation for a processed document the user owns."""
    document = await document_service.get_owned(db, user_id, document_id)
    if document.status is not DocumentStatus.COMPLETED:
        raise ConflictError("Insights can be generated once the document has been processed.")
    if not llm_configured(get_settings()):
        raise LLMNotConfiguredError("The AI model is not configured. Set LLM_API_KEY in .env and restart.")
    existing = await db.get(DocumentInsight, document_id)
    if (
        existing is not None
        and existing.status is InsightStatus.PENDING
        and datetime.now(UTC) - existing.requested_at < STALE_PENDING_AFTER
    ):
        raise ConflictError("Insights for this document are already being generated.")

    insight = await _mark_pending(db, document_id)
    if not await queue.enqueue_insights(document_id):
        insight.status = InsightStatus.FAILED
        insight.error_message = "Background processing is unavailable right now. Try again shortly."
        await db.commit()
    logger.info("insights_requested", extra={"document_id": str(document_id)})
    return _read(document_id, insight)


async def request_automatically(db: AsyncSession, queue: Any, document_id: uuid.UUID) -> None:
    """After a successful ingestion when DOCUMENT_INSIGHTS_AUTO is on. Best effort, never raises."""
    try:
        if not llm_configured(get_settings()):
            return
        await _mark_pending(db, document_id)
        if not await queue.enqueue_insights(document_id):
            insight = await db.get(DocumentInsight, document_id)
            if insight is not None:
                insight.status = InsightStatus.FAILED
                insight.error_message = "Background processing was unavailable. Generate the insights again."
                await db.commit()
    except Exception:
        logger.exception("insights_auto_request_failed", extra={"document_id": str(document_id)})


# --- generating (worker) -------------------------------------------------------------------------


@dataclass(slots=True)
class _Usage:
    input_tokens: int = 0
    output_tokens: int = 0
    calls: int = 0
    model: str | None = None


def _label(chunk: DocumentChunk) -> str:
    if chunk.page_number:
        return f"[Page {chunk.page_number}]"
    if chunk.section:
        return f"[Section: {chunk.section}]"
    return ""


def _select_passages(passages: list[str], budget: int) -> tuple[list[str], float]:
    """All passages if they fit in `budget` characters; otherwise an even sample across the
    document, in order. Returns (passages, share of characters kept)."""
    total = sum(len(p) for p in passages)
    if total <= budget or not passages:
        return passages, 1.0
    keep = max(1, int(len(passages) * budget / total))
    indexes = sorted({round(i * (len(passages) - 1) / max(keep - 1, 1)) for i in range(keep)})
    selected: list[str] = []
    used = 0
    for index in indexes:
        if used + len(passages[index]) > budget:
            break
        selected.append(passages[index])
        used += len(passages[index])
    return selected, used / total


def _split(passages: list[str], size: int) -> list[str]:
    parts: list[str] = []
    current: list[str] = []
    length = 0
    for passage in passages:
        if current and length + len(passage) > size:
            parts.append("\n\n".join(current))
            current, length = [], 0
        current.append(passage[:size])
        length += len(passage)
    if current:
        parts.append("\n\n".join(current))
    return parts


async def _analyse(llm: LLMProvider, system: str, text: str, usage: _Usage) -> dict[str, Any]:
    response = await llm.generate(
        system=system,
        messages=[Message.user(text)],
        max_tokens=_MAX_OUTPUT_TOKENS,
        effort=get_settings().insights_effort,
        json_schema=INSIGHT_SCHEMA,
    )
    usage.input_tokens += response.input_tokens
    usage.output_tokens += response.output_tokens
    usage.calls += 1
    usage.model = response.model
    if response.truncated:
        raise InsightGenerationError("The analysis was too long and was cut off. Try again.")
    try:
        data = json.loads(response.text)
        InsightContent.model_validate(data)  # shape check; cleaning happens on the final result
    except (json.JSONDecodeError, ValidationError) as exc:
        raise InsightGenerationError(
            "The AI model returned an analysis in an unexpected format. Try again."
        ) from exc
    return data


def _normalise(text: str) -> str:
    return " ".join(text.lower().split())


def _ground(content: InsightContent, source: str) -> InsightContent:
    """Keep only keywords and entity names that occur in the text the model read."""
    text = _normalise(source)
    keywords = [k for k in content.keywords if _normalise(k) in text]
    entities = [e for e in content.entities if _normalise(e.name) in text]
    removed = (len(content.keywords) - len(keywords)) + (len(content.entities) - len(entities))
    return content.model_copy(
        update={"keywords": keywords, "entities": entities, "ungrounded_removed": removed}
    )


async def generate(
    document_id: uuid.UUID,
    *,
    session_factory: async_sessionmaker[AsyncSession] = SessionLocal,
    llm: LLMProvider | None = None,
) -> InsightStatus | None:
    """Generate the pending insights for a document. Returns the final status, or None if there
    is nothing to do (no pending request, or the document is gone)."""
    settings = get_settings()
    log = {"document_id": str(document_id)}
    async with session_factory() as db:
        insight = await db.get(DocumentInsight, document_id)
        if insight is None or insight.status is not InsightStatus.PENDING:
            logger.info("insights_skipped", extra=log)
            return None
        chunks = list(
            await db.scalars(
                select(DocumentChunk)
                .where(DocumentChunk.document_id == document_id)
                .order_by(DocumentChunk.chunk_index)
            )
        )
        document = await db.get(Document, document_id)

        usage = _Usage()
        try:
            if not chunks or document is None:
                raise InsightGenerationError("The document has no indexed text to analyse.")
            llm = llm or llm_factory.get_llm_provider()
            passages = [f"{_label(c)}\n{c.content}".strip() for c in chunks]
            chars_per_call = settings.insights_chars_per_call
            selected, coverage = _select_passages(passages, chars_per_call * settings.insights_max_parts)
            parts = _split(selected, chars_per_call)
            header = f"Document: {document.filename}\n\n"
            if len(parts) == 1:
                data = await _analyse(llm, ANALYSIS_SYSTEM_PROMPT, header + parts[0], usage)
            else:
                partials = [
                    await _analyse(
                        llm, ANALYSIS_SYSTEM_PROMPT, f"{header}Part {i + 1} of {len(parts)}:\n\n{part}", usage
                    )
                    for i, part in enumerate(parts)
                ]
                data = await _analyse(
                    llm, MERGE_SYSTEM_PROMPT, header + json.dumps(partials, ensure_ascii=False), usage
                )
            content = _ground(InsightContent.model_validate(data), "\n".join(selected))
        except (InsightGenerationError, LLMError) as exc:
            message = exc.message if isinstance(exc, LLMError) else str(exc)
            return await _fail(db, insight, message, usage, log)
        except Exception:
            logger.exception("insights_generation_error", extra=log)
            return await _fail(db, insight, _GENERIC_FAILURE, usage, log)

        insight.status = InsightStatus.READY
        insight.content = content.model_dump(mode="json")
        insight.model = usage.model
        insight.input_tokens = usage.input_tokens
        insight.output_tokens = usage.output_tokens
        insight.llm_calls = usage.calls
        insight.coverage = round(coverage, 4)
        insight.error_message = None
        insight.generated_at = datetime.now(UTC)
        await db.commit()
    logger.info(
        "insights_generated",
        extra={
            **log,
            "llm_calls": usage.calls,
            "input_tokens": usage.input_tokens,
            "output_tokens": usage.output_tokens,
            "coverage": round(coverage, 4),
            "ungrounded_removed": content.ungrounded_removed,
        },
    )
    return InsightStatus.READY


async def _fail(
    db: AsyncSession, insight: DocumentInsight, message: str, usage: _Usage, log: dict[str, str]
) -> InsightStatus:
    # Nothing was written in this session before the failure, so the row is updated directly.
    insight.status = InsightStatus.FAILED
    insight.error_message = message
    insight.input_tokens = usage.input_tokens  # tokens spent on a failed run still count
    insight.output_tokens = usage.output_tokens
    insight.llm_calls = usage.calls
    await db.commit()
    logger.warning("insights_failed", extra={**log, "error": message, "llm_calls": usage.calls})
    return InsightStatus.FAILED


async def fail_abandoned(document_id: uuid.UUID, attempts: int) -> None:
    """Called when a job keeps crashing its worker (dead-lettered)."""
    async with SessionLocal() as db:
        insight = await db.get(DocumentInsight, document_id)
        if insight is not None and insight.status is InsightStatus.PENDING:
            insight.status = InsightStatus.FAILED
            insight.error_message = (
                f"Generation was stopped after {attempts} failed attempts. Try again later."
            )
            await db.commit()
